"use client";

import type { Metadata } from "next";
import React, { useState } from "react";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import localFont from "next/font/local";
import { useRouter, usePathname } from "next/navigation";
import {
  GithubFilled,
  InfoCircleFilled,
  QuestionCircleFilled,
} from "@ant-design/icons";
import { PageContainer, ProCard, ProLayout } from "@ant-design/pro-components";
import defaultProps from "./_defaultProps";

import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const router = useRouter();
  const pathname = usePathname();
  return (
    <html lang="en">
      <body>
        <AntdRegistry>
          <div
            id="test-pro-layout"
            style={{
              height: "100vh",
            }}
          >
            <ProLayout
              siderWidth={216}
              bgLayoutImgList={[
                {
                  src: "https://img.alicdn.com/imgextra/i2/O1CN01O4etvp1DvpFLKfuWq_!!6000000000279-2-tps-609-606.png",
                  left: 85,
                  bottom: 100,
                  height: "303px",
                },
                {
                  src: "https://img.alicdn.com/imgextra/i2/O1CN01O4etvp1DvpFLKfuWq_!!6000000000279-2-tps-609-606.png",
                  bottom: -68,
                  right: -45,
                  height: "303px",
                },
                {
                  src: "https://img.alicdn.com/imgextra/i3/O1CN018NxReL1shX85Yz6Cx_!!6000000005798-2-tps-884-496.png",
                  bottom: 0,
                  left: 0,
                  width: "331px",
                },
              ]}
              {...defaultProps}
              location={{
                pathname,
              }}
              avatarProps={{
                src: "https://gw.alipayobjects.com/zos/antfincdn/efFD%24IOql2/weixintupian_20170331104822.jpg",
                title: "七妮妮",
                size: "small",
              }}
              actionsRender={(props) => {
                if (props.isMobile) return [];
                return [
                  <InfoCircleFilled key="InfoCircleFilled" />,
                  <QuestionCircleFilled key="QuestionCircleFilled" />,
                  <GithubFilled key="GithubFilled" />,
                ];
              }}
              menuItemRender={(item, dom) => (
                <div
                  onClick={() => {
                    router.push(item.path!);
                  }}
                >
                  {dom}
                </div>
              )}
            >
              <PageContainer>
                <ProCard
                  style={{
                    height: "100vh",
                    minHeight: 800,
                  }}
                >
                  {children}
                </ProCard>
              </PageContainer>
            </ProLayout>
          </div>
        </AntdRegistry>
      </body>
    </html>
  );
}
